name: Build and Push Docker Containers

on:
  release:
    types: 
      - published # Only trigger on published releases

  workflow_dispatch: # Allows manual trigger from GitHub Actions UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME_WEB: ${{ github.repository }}/web
      IMAGE_NAME_CMS: ${{ github.repository }}/cms
      IMAGE_TAG: ${{ github.ref_name }} # Use the release tag name as the image tag

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: docker-cache-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            docker-cache-${{ github.ref_name }}-
            docker-cache-

      - name: Build & Push Web Container
        run: |
          docker build \
            -f ./web/Dockerfile \
            -t ${{ env.REGISTRY }}/$(echo ${{ env.IMAGE_NAME_WEB }} | tr '[:upper:]' '[:lower:]'):${{ env.IMAGE_TAG }} \
            ./web
          docker push ${{ env.REGISTRY }}/$(echo ${{ env.IMAGE_NAME_WEB }} | tr '[:upper:]' '[:lower:]'):${{ env.IMAGE_TAG }}

      - name: Build & Push CMS Container
        run: |
          docker build \
            -f ./cms/Dockerfile \
            -t ${{ env.REGISTRY }}/$(echo ${{ env.IMAGE_NAME_CMS }} | tr '[:upper:]' '[:lower:]'):${{ env.IMAGE_TAG }} \
            ./cms
          docker push ${{ env.REGISTRY }}/$(echo ${{ env.IMAGE_NAME_CMS }} | tr '[:upper:]' '[:lower:]'):${{ env.IMAGE_TAG }}

      - name: Clean up Docker images
        run: docker system prune -f --volumes
