FROM node:20.20.2-bookworm

WORKDIR /app

COPY ./package.json .
COPY ./package-lock.json .

RUN npm ci

COPY ./ .


ARG PRIMARY_COLOR
ARG SECONDARY_COLOR

ENV PRIMARY_COLOR=${PRIMARY_COLOR}
ENV SECONDARY_COLOR=${SECONDARY_COLOR}

EXPOSE 3000

CMD ["npm", "run", "develop"]
